src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BookRepository::class)
 */
class Book
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $cover;

    /**
     * @ORM\Column(type="date")
     */
    private $release_date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $author;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $genre;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_reserved;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_borrowed;

    /**
     * @ORM\OneToOne(targetEntity=Reservation::class, mappedBy="book", cascade={"persist", "remove"})
     */
    private $reservation;

    public function __construct()
    {
        $this->is_reserved = false;
        $this->is_borrowed = false;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getCover(): ?string
    {
        return $this->cover;
    }

    public function setCover(string $cover): self
    {
        $this->cover = $cover;

        return $this;
    }

    public function getReleaseDate(): ?\DateTimeInterface
    {
        return $this->release_date;
    }

    public function setReleaseDate(\DateTimeInterface $release_date): self
    {
        $this->release_date = $release_date;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(string $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    public function getIsReserved(): ?bool
    {
        return $this->is_reserved;
    }

    public function setIsReserved(bool $is_reserved): self
    {
        $this->is_reserved = $is_reserved;

        return $this;
    }

    public function getIsBorrowed(): ?bool
    {
        return $this->is_borrowed;
    }

    public function setIsBorrowed(bool $is_borrowed): self
    {
        $this->is_borrowed = $is_borrowed;

        return $this;
    }

    public function getReservation(): ?Reservation
    {
        return $this->reservation;
    }

    public function setReservation(Reservation $reservation): self
    {
        // set the owning side of the relation if necessary
        if ($reservation->getBook() !== $this) {
            $reservation->setBook($this);
        }

        $this->reservation = $reservation;

        return $this;
    }
}

src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReservationRepository::class)
 */
class Reservation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="reservations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\OneToOne(targetEntity=Book::class, inversedBy="reservation", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $book;

    /**
     * @ORM\Column(type="date")
     */
    private $reserved_date;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $borrowed_date;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getBook(): ?Book
    {
        return $this->book;
    }

    public function setBook(Book $book): self
    {
        $this->book = $book;

        return $this;
    }

    public function getReservedDate(): ?\DateTimeInterface
    {
        return $this->reserved_date;
    }

    public function setReservedDate(\DateTimeInterface $reserved_date): self
    {
        $this->reserved_date = $reserved_date;

        return $this;
    }

    public function getBorrowedDate(): ?\DateTimeInterface
    {
        return $this->borrowed_date;
    }

    public function setBorrowedDate(?\DateTimeInterface $borrowed_date): self
    {
        $this->borrowed_date = $borrowed_date;

        return $this;
    }
}

src/Controller/CatalogueController.php
<?php

namespace App\Controller;

use App\Entity\Book;
use App\Entity\Reservation;
use App\Repository\BookRepository;
use App\Repository\ReservationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CatalogueController extends AbstractController
{
    /**
     * @Route("/catalogue", name="catalogue")
     * @IsGranted("ROLE_USER")
     */
    public function index(BookRepository $bookRepository): Response
    {
        $user = $this->getUser();

        if(!$user->getUserValidated())
        {
            return $this->render('home/userUnValidated.html.twig',  []);
        }

        return $this->render('catalogue/index.html.twig', [
            'books' => $bookRepository->findAll()
        ]);
    }

    /**
     * @Route("/borrow", name="borrow")
     * @IsGranted("ROLE_USER")
     */
    public function borrow(ReservationRepository $reservationRepository): Response
    {
        $user = $this->getUser();
        return $this->render('catalogue/borrowed.html.twig', [
            'reservations' => $reservationRepository->findBy(['user'=>$user])
        ]);
    }

    /**
     * @Route("/catalogue/{id}", name="editBook")
     */
    public function show(Book $book): Response
    {
        return $this->render('catalogue/edit.html.twig', [
            'book' => $book
        ]);
    }


    /**
     * Permet de reserver un livre
     *
     * @Route("/catalogue/{id}/reserve", name="reserveBook")
     *
     * @param Book $book
     * @param EntityManagerInterface $manager
     * @param ReservationRepository $reservationRepository
     * @return Response
     */
    public function reserveBook(Book $book, EntityManagerInterface $manager, ReservationRepository $reservationRepository) : Response
    {
        $user = $this->getUser();

        if(!$user) return $this->json([
            'code' => 403,
            'message' => "Non autorisé"
        ], 403);

        // if($book->isReservedByUser($user)) {
        $resa = $reservationRepository->findOneBy([
            'book' => $book,
            'user' => $user
        ]);
        if($resa) {

            $manager->remove($resa);
            $book->setIsReserved(false);
            $manager->flush();

            return $this->redirectToRoute('catalogue');
        }

        $reservation = new Reservation();
        $reservation->setBook($book)
            ->setUser($user)
            ->setReservedDate(new \DateTime('now'));
        $manager->persist($reservation);

        $book->setIsReserved(true);

        $manager->flush();

        return $this->redirectToRoute('catalogue');
    }
}

templates/catalogue/borrowed.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% block stylesTwig %}
        <style>
            .body{
                margin: 0;
                padding: 10px;
                min-height: calc(100vh - 260px);
            }
            .container{
                background-color: black;
                justify-content: center;
                align-items: center;
                padding: 20px;
                min-height: 680px;
            }
            .subContainer{
                background-color: black;
            }
            .formContainer{
                display: flex;
                background-color: black;
                justify-content: center;
                align-items: center;
            }
            .navbar{
                min-height: 60px;
            }
            .ToggleIcon{
                padding: 5px;
                border-radius: 50%;
                border: solid 1px white;
            }
            .Link-Collapse{
                text-decoration: none;
                margin-right: 25px;
                font-size: 20px;
                text-align: center;
                color: #7ACBCD;
                margin-top: 15px;
                margin-bottom: 15px;
                font-weight: 500;
                transition: 0.5s;
            }
            .Link-Collapse:hover {
                color: #7ACBCD;
                font-size: 18px;
                transition: 0.5s;
            }
            .Link-Collapse:focus {
                color: #7ACBCD;
            }
            .title{
                color: #7ACBCD;
                display: inline-flex;
                margin: 0;
                padding: 0;
                font-size: 34px;
            }
            .name {
                color: #7ACBCD;
            }
            a {
                text-decoration: none;
            }
            .LabelForm{
                display: block;
            }
            #registration_form_prenom, #registration_form_nom, #registration_form_adresse_postal, #registration_form_email, #registration_form_plainPassword{
                border-radius: 20px;
                margin-bottom: 10px;
                width: 100%;
            }
            #registration_form_date_naissance_month, #registration_form_date_naissance_day, #registration_form_date_naissance_year {
                border-radius: 20px;
                margin-bottom: 10px;
                margin-right: 10px;
            }
            #registration_form_agreeTerms{
                margin-left: 10px;
            }
            .LogoImage {
                height: 120px;
                width: 120px;
                border-radius: 100%;
                margin-top: 20px;
                margin-bottom: 20px;
                border: solid 2px #7ACBCD;
            }
            .errorMessage{
                color: red;
            }
            .Button-Register{
                margin-top: 20px;
                color: white;
                border: solid 2px #7ACBCD;
                background-color: black;
                padding: 5px;
                border-radius: 15px;
                transition: 0.5s;
            }
            .Button-Register:hover {
                transition: 0.5s;
                margin-left: 10px;
                border: solid 2px white;
                color: black;
                background-color: #7ACBCD;
                border-radius: 25px;
            }
            .ChangeAuth{
                margin-top: 20px;
                color: white;
            }
            .LinkAuth{
                color: #7ACBCD;
                transition: 0.5s;
            }
            .LinkAuth:hover{
                transition: 0.5s;
                color: #7ACBCD;
            }
            .fixTop{
                margin-top: 150px;
            }
            @media (min-width: 1024px) and (max-width: 3000px) {
                .container{
                    margin-top: 80px;
                    margin-bottom: 80px;
                }
                .fixMargin {
                    margin-top: 80px;
                }
            }
            @media (min-width: 776px) and (max-width: 1024px) {
                .container{
                    margin-top: 40px;
                    margin-bottom: 40px;
                }
                .fixMargin {
                    margin-top: 40px;
                }
            }
            @media (max-width: 991px) {
                .Link-Collapse{
                    color: white;
                    text-align: center;
                }
            }
            @media (max-width: 600px) {
                .title{
                    font-size: 28px;
                    margin-left: 15px;
                }
                .body{
                    min-height: calc(100vh - 160px);
                }
                .fixTop{
                    margin-top: 50px;
                }
                .fixMargin {
                    margin-top: 25px;
                }
            }
            @media (max-width: 475px) {
                .title{
                    font-size: 18px;
                }
            }
            @media (max-width: 375px) {
                .title{
                    font-size: 24px;
                    text-align: center;
                    margin-left: 15px;
                }
            }
            @media (max-width: 312px) {
                .title{
                    font-size: 18px;
                }
            }
        </style>
    {% endblock stylesTwig %}
    {% block navHeader %}
        <nav class="navbar navbar-expand-lg Header-Container fixed-top">
            <div class="container-fluid">
                <img src="{{ asset('build/images/Logo.38d6610a.jpeg') }}" class="Logo" alt="Logo" >
                <h1 class="navbar-brand title">La Chapelle-Curreaux</h1>
                <button class="navbar-toggler Button-Toggle" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fas fa-bars ToggleIcon"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        {% if app.user %}
                            <li class="nav-item">
                                <a class="nav-link active Link-Collapse" href="{{ path('catalogue') }}">Catalogue</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link Link-Collapse" href="{{ path('borrow') }}">Emprunts</a>
                            </li>
                        {% endif %}
                        {%  if is_granted('ROLE_EMPLOYEE') %}
                            <li class="nav-item">
                                <a class="nav-link Link-Collapse" href="{{ path('admin') }}" target="_blank">Administration</a>
                            </li>
                        {%  endif %}

                        {% if not app.user %}
                            <li class="nav-item">
                                <a class="nav-link Link-Collapse" href="{{ path('app_register') }}">S'enregistrer</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link Link-Collapse" href="{{ path('app_login') }}">Se connecter</a>
                            </li>
                        {% endif %}

                        {% if app.user %}
                            <li class="nav-item">
                                <a class="nav-link Link-Collapse" href="{{ path('app_logout') }}">Logout</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    {% endblock navHeader %}

    <div class="body fixTop">
        <div class="col mx-1">
            <div class="row py-2">
                <div class="col">
                    {% if app.user %}
                        <h4 style="color: #7ACBCD">Bienvenue, {{ app.user.prenom }}.</h4>
                    {% endif %}
                    <h4 class="fixMargin">Liste de réservations : </h4>
                    <table class="table table-striped table-hover text-center align-middle">
                        <thead>
                        <tr>
                            <th scope="col"></th>
                            <th scope="col">Nom du livre</th>
                            <th scope="col">Date de réservation</th>
                            <th scope="col">Récupérer avant le</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for resa in reservations %}
                            {% if not resa.book.isBorrowed %}
                                <tr>
                                    <td><img src="{{ resa.book.cover }}" class="img-fluid rounded-start h-100" style="width:100px" alt="book cover"></td>
                                    <td>{{ resa.book.title }}</td>
                                    <td>{{ resa.reservedDate | date('d-m-Y') }}</td>
                                    <td>{{ resa.reservedDate|date_modify("+3 day") | date('d-m-Y') }}</td>
                                </tr>
                            {%  endif %}
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <div class="col mx-1">
            <div class="row py-2"  >
                <div class="col">
                <h4>Liste d'emprunts  : </h4>
                    <table class="table table-striped table-hover text-center align-middle">
                        <thead>
                            <tr>
                                <th scope="col"></th>
                                <th scope="col">Nom du livre</th>
                                <th scope="col">Date d'emprunt</th>
                                <th scope="col">Rendre avant le</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for resa in reservations %}
                            {% if resa.book.isBorrowed %}
                                <tr>
                                    <td><img src="{{ resa.book.cover }}" class="img-fluid rounded-start h-100" style="width:100px" alt="book cover"></td>
                                    <td>{{ resa.book.title }}</td>
                                    <td>{{ resa.borrowedDate | date('d-m-Y') }}</td>
                                    <td>{{ resa.borroweddate|date_modify("+3 week") | date('d-m-Y') }}</td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    {% block Footer %}
        <div class="Footer">
            <h6>© Chapelle-Curreaux</h6>
        </div>
    {% endblock Footer %}
{% endblock %}

templates/catalogue/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% block navHeader %}
        <nav class="navbar navbar-expand-lg Header-Container fixed-top">
            <div class="container-fluid">
                <img src="{{ asset('build/images/Logo.38d6610a.jpeg') }}" class="Logo" alt="Logo" >
                <h1 class="navbar-brand title">La Chapelle-Curreaux</h1>
                <button class="navbar-toggler Button-Toggle" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fas fa-bars ToggleIcon"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        {% if app.user %}
                            <li class="nav-item">
                                <a class="nav-link active Link-Collapse" href="{{ path('catalogue') }}">Catalogue</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link Link-Collapse" href="{{ path('borrow') }}">Emprunts</a>
                            </li>
                        {% endif %}
                        {%  if is_granted('ROLE_EMPLOYEE') %}
                            <li class="nav-item">
                                <a class="nav-link Link-Collapse" href="{{ path('admin') }}" target="_blank">Administration</a>
                            </li>
                        {%  endif %}

                        {% if not app.user %}
                            <li class="nav-item">
                                <a class="nav-link Link-Collapse" href="{{ path('app_register') }}">S'enregistrer</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link Link-Collapse" href="{{ path('app_login') }}">Se connecter</a>
                            </li>
                        {% endif %}

                        {% if app.user %}
                            <li class="nav-item">
                                <a class="nav-link Link-Collapse" href="{{ path('app_logout') }}">Logout</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    {% endblock navHeader %}
    {% block stylesTwig %}
        <style>
            .body{
                margin: 0;
                padding: 10px;
                min-height: calc(100vh - 260px);
            }
            .container{
                background-color: black;
                justify-content: center;
                align-items: center;
                padding: 20px;
                min-height: 680px;
            }
            .subContainer{
                background-color: black;
            }
            .formContainer{
                display: flex;
                background-color: black;
                justify-content: center;
                align-items: center;
            }
            .navbar{
                min-height: 60px;
            }
            .ToggleIcon{
                padding: 5px;
                border-radius: 50%;
                border: solid 1px white;
            }
            .Link-Collapse{
                text-decoration: none;
                margin-right: 25px;
                font-size: 20px;
                text-align: center;
                color: #7ACBCD;
                margin-top: 15px;
                margin-bottom: 15px;
                font-weight: 500;
                transition: 0.5s;
            }
            .Link-Collapse:hover {
                color: #7ACBCD;
                font-size: 18px;
                transition: 0.5s;
            }
            .Link-Collapse:focus {
                color: #7ACBCD;
            }
            .title{
                color: #7ACBCD;
                display: inline-flex;
                margin: 0;
                padding: 0;
                font-size: 34px;
            }
            .name {
                color: #7ACBCD;
            }
            a {
                text-decoration: none;
            }
            .LabelForm{
                display: block;
            }
            #registration_form_prenom, #registration_form_nom, #registration_form_adresse_postal, #registration_form_email, #registration_form_plainPassword{
                border-radius: 20px;
                margin-bottom: 10px;
                width: 100%;
            }
            #registration_form_date_naissance_month, #registration_form_date_naissance_day, #registration_form_date_naissance_year {
                border-radius: 20px;
                margin-bottom: 10px;
                margin-right: 10px;
            }
            #registration_form_agreeTerms{
                margin-left: 10px;
            }
            .LogoImage {
                height: 120px;
                width: 120px;
                border-radius: 100%;
                margin-top: 20px;
                margin-bottom: 20px;
                border: solid 2px #7ACBCD;
            }
            .errorMessage{
                color: red;
            }
            .Button-Register{
                margin-top: 20px;
                color: white;
                border: solid 2px #7ACBCD;
                background-color: black;
                padding: 5px;
                border-radius: 15px;
                transition: 0.5s;
            }
            .Button-Register:hover {
                transition: 0.5s;
                margin-left: 10px;
                border: solid 2px white;
                color: black;
                background-color: #7ACBCD;
                border-radius: 25px;
            }
            .ChangeAuth{
                margin-top: 20px;
                color: white;
            }
            .LinkAuth{
                color: #7ACBCD;
                transition: 0.5s;
            }
            .LinkAuth:hover{
                transition: 0.5s;
                color: #7ACBCD;
            }
            .fixTop{
                margin-top: 150px;
            }
            @media (min-width: 1024px) and (max-width: 3000px) {
                .container{
                    margin-top: 80px;
                    margin-bottom: 80px;
                }
            }
            @media (min-width: 776px) and (max-width: 1024px) {
                .container{
                    margin-top: 40px;
                    margin-bottom: 40px;
                }
            }
            @media (max-width: 991px) {
                .Link-Collapse{
                    color: white;
                    text-align: center;
                }
            }
            @media (max-width: 600px) {
                .title{
                    font-size: 28px;
                    margin-left: 15px;
                }
                .body{
                    min-height: calc(100vh - 160px);
                }
                .fixTop{
                    margin-top: 50px;
                }
            }
            @media (max-width: 475px) {
                .title{
                    font-size: 18px;
                }
            }
            @media (max-width: 375px) {
                .title{
                    font-size: 24px;
                    text-align: center;
                    margin-left: 15px;
                }
            }
            @media (max-width: 312px) {
                .title{
                    font-size: 18px;
                }
            }
        </style>
    {% endblock stylesTwig %}
    <div class="body fixTop">
        <div class="d-flex justify-content-center mt-2">
            <div class="row" >
                <div class="col">
                    <div class="card p-4 shadow-lg bg-light-gray" style="max-width: 840px;overflow: hidden; border-radius: 50px; border: solid 2px #7ACBCD">
                        <h4 class="ribbon shadow-lg text-center mb-4"
                            style="display: {{ book.isReserved ? 'block' : 'none' }};color: #7ACBCD; background-color: black; border-radius: 50px; border: solid 2px #7ACBCD">
                            Réservé
                        </h4>
                        <div class="row g-0">
                            <div class="col d-flex align-items-center">
                                <img src="{{ book.cover }}" class="card-img-top rounded" alt="cover image">
                            </div>
                            <div class="col-md-8">
                                <div class="card-body d-flex flex-column align-items-start justify-content-between h-100">
                                    <h5 class="card-title">{{ book.title }}</h5>
                                    <p class="card-text">{{ book.description }}</p>
                                    <p class="card-text"><small class="text-muted">{{ book.genre }}</small></p>
                                    <div style="display: flex; align-items: center; justify-content: space-between; align-self: end">
                                        <a href="{{ path('catalogue') }}" class="Button-Ok text-white">Retour</a>
                                        {% if book.isReserved %}
                                            {% if book.reservation and app.user.prenom is same as book.reservation.user.prenom  %}
                                                {% if book.isBorrowed %}
                                                    <div class="bg-info p-2 rounded">Merci de rapporter ce livre</div>
                                                {% else %}
                                                    <a href="{{ path('reserveBook',{'id': book.id }) }}" class="Button-Ok text-white" style="margin-left: 20px">
                                                        Annuler la réservation
                                                    </a>
                                                {% endif %}
                                            {% else %}
                                            {% endif %}
                                        {% else %}
                                            <a href="{{ path('reserveBook',{'id': book.id }) }}" class="Button-Ok text-white" style="margin-left: 20px">
                                                Réserver
                                            </a>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    {% block Footer %}
        <div class="Footer">
            <h6>© Chapelle-Curreaux</h6>
        </div>
    {% endblock Footer %}
{% endblock %}